server:
  port: 7071
spring:
  profiles:
    active: dev

  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp


mybatis:
  config-location: classpath:mybatis/config/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
